create table transfer_agent (
  transfer_agent_id varchar2(128) primary key,
  name varchar2(256) not null,
  enabled number(1) default 1 not null,
  created_at timestamp default systimestamp not null
);

create table agent_port_assignment (
  transfer_agent_id varchar2(128) not null references transfer_agent(transfer_agent_id),
  data_udp_port number not null,
  management_endpoint varchar2(512),
  constraint agent_port_assignment_pk primary key (transfer_agent_id, data_udp_port)
);

create table registry_account (
  account_id number generated by default as identity primary key,
  transfer_agent_id varchar2(128) not null references transfer_agent(transfer_agent_id),
  registry_url varchar2(1024) not null,
  username varchar2(256) not null,
  secret_ref varchar2(512) not null,
  created_at timestamp default systimestamp not null
);

create table artifact_presence (
  transfer_agent_id varchar2(128) not null references transfer_agent(transfer_agent_id),
  artifact_type varchar2(32) not null,
  artifact_key varchar2(2048) not null,
  artifact_sha256 varchar2(64) not null,
  seen_count number default 1 not null,
  last_seen_at timestamp default systimestamp not null,
  deleted_at timestamp,
  constraint artifact_presence_pk primary key (transfer_agent_id, artifact_type, artifact_key)
);

create table transfer_batch (
  batch_id varchar2(128) primary key,
  transfer_agent_id varchar2(128) not null references transfer_agent(transfer_agent_id),
  content_type varchar2(32) not null,
  total_objects number not null,
  status varchar2(32) not null,
  created_at timestamp default systimestamp not null,
  completed_at timestamp
);
